# Generated by Django 4.0.4 on 2023-06-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0002_globaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldata',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
