# Generated by Django 4.0.4 on 2023-06-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0003_alter_globaldata_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='oldUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='GlobalData',
        ),
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
