# Generated by Django 4.0.4 on 2023-06-11 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0006_app_database_delete_newuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='global_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
                ('location', models.CharField(max_length=25)),
                ('spam', models.IntegerField(default=0)),
            ],
        ),
    ]
