# Generated by Django 4.0.4 on 2023-06-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_database',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='global_database',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
