# Generated by Django 4.0.4 on 2023-06-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0009_app_database_is_spam_global_database_is_spam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='global_database',
            name='is_spam',
        ),
    ]
