# Generated by Django 4.0.4 on 2023-06-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0010_remove_global_database_is_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
