# Generated by Django 4.0.4 on 2023-06-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0011_contact_is_spam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
